import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
// for auth
import { SessionProvider } from "@/context/sessionContext";
import { auth } from "@/auth";
import { headers } from "next/headers";
import { ModalProvider } from "@/components/providers/modal-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeHUB",
  description: "Generated by create next app",
  icons: {
    icon : [
      {
      media : "(prefers-color-scheme :light)",
      url : "/logo.svg",
      href : "/logo.svg",

      }
      ,
      {
        media : "(prefers-color-scheme :dark)",
        url : "/logo.svg",
        href : "/logo.svg",
        }
    ]
  }
};




            /* we made this async for session await */
export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {


    const session = await auth.api.getSession({
      headers: await headers(),
    });
  
  return (


    <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <SessionProvider initialSession={session}>
          <ModalProvider/>
            {children}

          </SessionProvider>
          </ThemeProvider>
        </body>
      </html>
    
  );
}
